import Person from "../models/Person";

export const mockPeople = [
    new Person({ name: "Steve", id: "1" }),
    new Person({ name: "Steve", id: "2" }),
    new Person({ name: "Amanda", id: "3" }),
    new Person({ name: "Timothy (Tim)", id: "4" }),
    new Person({ name: "Elliot", id: "5" }),
    new Person({ name: "Steve", id: "6" }),
    new Person({ name: "Jared", id: "7" }),
    new Person({ name: "Kate", id: "8" }),
    new Person({ name: "Oliver", id: "9" }),
    new Person({ name: "Luke", id: "10" }),
    new Person({ name: "Lucy", id: "11" }),
    new Person({ name: "Valentina (Val)", id: "12" }),
    new Person({ name: "Sebastian", id: "13" }),
    new Person({ name: "William (Will)", id: "14" }),
    new Person({ name: "Amanda", id: "15" }),
    new Person({ name: "Timothy (Tim)", id: "16" }),
    new Person({ name: "Elliot", id: "17" }),
    new Person({ name: "Steve", id: "18" }),
    new Person({ name: "Jared", id: "19" }),
    new Person({ name: "Kate", id: "20" }),
    new Person({ name: "Oliver", id: "21" }),
    new Person({ name: "Luke", id: "22" }),
    new Person({ name: "KingCaractacushasalongname", id: "23" }),
    new Person({ name: "Valentina (Val)", id: "24" }),
    new Person({ name: "Sebastian", id: "25" }),
    new Person({ name: "William (Will)", id: "26" }),
    new Person({ name: "Amanda", id: "27" }),
    new Person({ name: "Timothy (Tim)", id: "28" }),
    new Person({ name: "Elliot", id: "29" }),
    new Person({ name: "Steve", id: "30" }),
    new Person({ name: "Jared", id: "31" }),
    new Person({ name: "Kate", id: "32" }),
    new Person({ name: "Oliver", id: "33" }),
    new Person({ name: "Luke", id: "34" }),
    new Person({ name: "Lucy", id: "35" }),
    new Person({ name: "Valentina (Val)", id: "37" }),
    new Person({ name: "Sebastian", id: "38" })
];
